
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/db_tasks}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:123456}

api.security.token.secret=${JWT_SECRET:minha-chave-secreta-super-segura-para-dev-local}

recaptcha.secret-key=${RECAPTCHA_SECRET}
server.port=${PORT:8080}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect