# Configura\u00E7\u00E3o do Banco de Dados
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/db_tasks}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:123456}

# Configura\u00E7\u00F5es do Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# Segredos e Configura\u00E7\u00F5es
api.security.token.secret=${JWT_SECRET:minha-chave-secreta-local-12345}
recaptcha.secret-key=${RECAPTCHA_SECRET:6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe}

# Servidor e Porta do Railway
server.address=0.0.0.0
server.port=${PORT:8080}